export const strings = {
  appName: "코너브랜드 - 회개와천국복음선교회",
  tagline: "이미지/PDF 코너에 로고를 자동으로 삽입합니다.",
  pickFiles: "파일 선택",
  run: "로고 삽입 실행",
  filesTitle: "대상 파일 (이미지/PDF)",
  filesHelp: "여러 파일을 끌어놓거나, 이 섹션의 파일 선택 버튼으로 추가하세요.",
  dropTitle: "여기에 파일을 드래그하여 놓으세요",
  dropHint: "지원: JPG / PNG / WebP / PDF",
  logoImageTitle: "로고 이미지 (삽입할 이미지)",
  logoImageHelp: "기본값은 앱 기본 로고를 사용합니다.",
  pickLogoFile: "로고 파일 선택",
  useDefaultLogo: "기본 로고 사용",
  defaultLogoPath: "기본 로고: logo.png",
  outputDirTitle: "저장 위치",
  outputDirHelp: "기본값은 입력 파일 폴더의 CornerBrand_Output입니다.",
  pickOutputDir: "저장 위치 선택",
  useDefaultOutputDir: "기본값 사용",
  defaultOutputDir: "기본값: 입력 폴더의 CornerBrand_Output",
  settingsTitle: "설정",
  settingsHelp: "로고 위치와 크기(%)를 정한 뒤 실행하세요.",
  positionLabel: "삽입 위치",
  sizeLabel: "로고 크기(%)",
  updateCheckOnLaunchLabel: "앱 시작 시 업데이트 확인",
  updateCheckOnLaunchHelp: "끄면 실행 시 자동 업데이트 확인을 건너뜁니다.",
  updateCheckIntervalLabel: "업데이트 확인 간격(분)",
  updateCheckIntervalHelp: "0이면 앱을 켤 때마다 확인하고, 1~1440은 마지막 확인 이후 분 단위 간격입니다.",
  outputTitle: "출력",
  outputHelp: "기본값은 별도 폴더 저장입니다(원본은 변경하지 않음).",
  placeholderRow: "(예시) 파일이 여기 표시됩니다",
  placeholderRight: "(예시) 실행하면 결과가 여기 표시됩니다",
  missingLogo: "아이콘 파일을 찾지 못했습니다. icon.png 또는 logo.webp를 확인하세요.",
  unsupportedFiles: "지원하지 않는 파일 형식이 포함되어 제외했습니다.",
  clearList: "목록 비우기",
  removeOne: "삭제",
  notReadyEngine: "처리 엔진은 아직 준비 중입니다.",
  processing: "처리 중...",
  progressStatus: "진행",
  currentFileLabel: "현재 파일:",
  runFailed: "실행 중 오류가 발생했습니다.",
  pickerFailed: "파일 선택 창을 여는 중 오류가 발생했습니다.",
  resultSummaryPrefix: "성공",
  resultSummaryDivider: "건 / 실패",
  resultSummaryTail: "건 (총",
  resultSummaryTotalUnit: "건)",
  outputPathLabel: "출력:",
  errorLabel: "오류:",
  unknownError: "알 수 없는 오류",
  resultSuccess: "성공",
  resultFailure: "실패",
  footerRunStatus: "현재 선택 파일 {count}개",
  appVersionLabel: "앱 버전",
  manualUpdateCheck: "업데이트 확인",
  updateNoUpdate: "최신 버전을 사용 중입니다.",
  updateConfirm:
    "새 업데이트(v{version})가 있습니다. 지금 설치할까요?\n\n변경 사항:\n{notes}\n\n설치 중에는 잠시 기다려 주세요.",
  updateNoNotes: "릴리즈 노트가 없습니다.",
  updateDownloading: "업데이트 다운로드 중",
  updatePercentPrefix: "진행률:",
  updatePercentUnknown: "진행률: 계산 중",
  updateBytesPrefix: "다운로드:",
  updateBytesUnit: "bytes",
  updateInstalled: "업데이트가 설치되었습니다. 앱을 종료한 뒤 다시 실행해 주세요.",
  updateCheckFailed: "업데이트 확인 실패",
  fatalTitle: "앱 오류가 발생했습니다",
  fatalGuide: "앱을 다시 실행해 주세요. 문제가 계속되면 로그를 알려주세요.",
  fatalErrorLabel: "오류 메시지:",
} as const;
